
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '10.0'
use_frameworks!

target 'NeverMiss-iOS' do
  pod 'NVActivityIndicatorView'
  pod 'lottie-ios'
  pod 'Alamofire', '~> 4.7'
  pod 'ObjectMapper', '~> 3.1'
  pod 'PromiseKit/Alamofire', '~> 6.0'
  pod 'AFDateHelper', '~> 4.2.2'
  pod 'SwiftKeychainWrapper'
  pod 'Kingfisher', '~> 4.0'
end



